### ISSUE TITLE
Support for batch file upload in a nested folder/file structure

### ISSUE THREAD

**Issue by seitay** [seitay/neuroviewer#12]
It would be useful to have a support for batch file upload in a nested folder/file structure.  Currently, only a collection of SWC/ESWC can be loaded in a single folder.  There are cases where files are stored in nested folders.

**Comment by chestrada** [comment]
Nested (recursive) folder traversal works for Google Drive so far.
- Missing for local uploads

**Comment by chestrada** [comment]
Note: (Nested) local folder uploads can't be upload directly via input tag (like single/batch files can). Instead, they must have their own upload method - considering drag-and-drop upload for folders - 
see [source](https://stackoverflow.com/a/42633404/10998030) for evidence
