### ISSUE TITLE
Display toggling of imported neuron files.

### ISSUE THREAD

**Issue by seitay** [seitay/neuroviewer#8]
The user would want to toggle on/off of the display of imported neuron reconstructed files.  A feature would be nice to have a control on imported neurons.

**Comment by chestrada** [comment]
Some notes for this feature:

- Implement a checkbox feature for loading selected neurons - **Done** (went w/ toggle btn instead)
- Keep focus feature as a function but comment out for now (to avoid unloading all other neurons)  - **Done** (toggling a neuron off then on will achieve this affect)

**Comment by chestrada** [comment]
Bugs to solve with this feature:
- Strange behavior when uploading 100+ files - **Resolved**
- Toggling all neurons off, then only 1 on has many neurons loaded into the viewer - **Resolved**
- toggle btn bug: - **Resolved**
   Steps to recreate: 
        _Clear the viewer using toggle-all (to 'off' status), 
        then toggle search for 1 neuron, and toggle the one to 'on' status
        then clear the search..._ 
    Expected result: _only one neuron in the list will have its status to 'on',_ 
    _but many have them on although not present in viewer._

**Comment by chestrada** [comment]
Last bug (really just unwanted behavior):
- Position of viewer changes constantly when toggling off files, set a pin to the view that only changes when toggling a neuron on. 

**Making this a seperate issue**
